import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');
await page.locator('#map').waitFor();
await page.screenshot({path:'/tmp/padwork-empty.png'});
await page.locator('#map').click({position:{x:260,y:300}});
assert.equal(await page.locator('#cone-count').textContent(),'1');
await page.locator('#undo').click();assert.equal(await page.locator('#cone-count').textContent(),'0');
await page.locator('#redo').click();assert.equal(await page.locator('#cone-count').textContent(),'1');
await page.locator('[data-tool=stage]').click();await page.locator('#map').click({position:{x:200,y:430}});
await page.locator('#item-angle').fill('15');await page.locator('#item-angle').press('Tab');
assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))).items.find(i=>i.kind==='stage').angle,15);
await page.locator('[data-tool=start]').click();await page.locator('#map').click({position:{x:200,y:350}});
await page.locator('[data-tool=finish]').click();await page.locator('#map').click({position:{x:500,y:350}});
await page.locator('#item-angle').fill('90');await page.locator('#item-angle').press('Tab');
assert.equal(await page.locator('#item-angle').inputValue(),'90');
await page.locator('[data-tool=cone]').click();
const beforeMove=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork')));
const mapBox=await page.locator('#map').boundingBox();
await page.mouse.move(mapBox.x+260,mapBox.y+300);await page.mouse.down();await page.mouse.move(mapBox.x+290,mapBox.y+320,{steps:5});await page.mouse.up();
const afterMove=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork')));
assert.equal(afterMove.items.length,beforeMove.items.length);
assert.equal(afterMove.items[0].id,beforeMove.items[0].id);
assert.ok(afterMove.items[0].x>beforeMove.items[0].x);
assert.ok(afterMove.items[0].z>beforeMove.items[0].z);
assert.ok(Math.abs(afterMove.items[0].x/.3048-Math.round(afterMove.items[0].x/.3048))<1e-8);
await page.locator('#undo').click();assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))),beforeMove);
await page.locator('#redo').click();assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))),afterMove);
const saved=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork')));
await page.locator('#new').click();assert.equal(await page.locator('#cone-count').textContent(),'0');
await page.locator('#file').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});
await page.waitForFunction(()=>document.querySelector('#cone-count').textContent==='1');
assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))),saved);
await page.reload();assert.equal(await page.locator('#cone-count').textContent(),'1');
await page.locator('#export').click();
const dl=page.waitForEvent('download');await page.locator('#download-package').click();const file=await dl;assert.match(file.suggestedFilename(),/source.zip$/);
await page.locator('#close-export').click();
await page.locator('[data-tool=pointer]').click();
await page.locator('#map').click({position:{x:340,y:330}});
await page.keyboard.press('r');
assert.equal(await page.locator('#item-angle').inputValue(),'15');
await page.locator('#item-angle').fill('90');await page.locator('#item-angle').press('Tab');
await page.locator('#map').click({position:{x:360,y:350}});
let pointers=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))).items.filter(i=>i.kind==='pointer');
assert.equal(pointers.length,2);assert.equal(pointers[0].angle,90);
await page.locator('#undo').click();
pointers=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))).items.filter(i=>i.kind==='pointer');assert.equal(pointers.length,1);
await page.locator('#redo').click();
await page.reload();assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))).items.filter(i=>i.kind==='pointer').length,2);
await page.locator('#help').click();await page.locator('#help-dialog').waitFor({state:'visible'});await page.keyboard.press('Escape');
await page.locator('#demo').click();assert.equal(await page.locator('#cone-count').textContent(),'301');
assert.equal(await page.locator('#site-size').textContent(),'975 × 1400 ft');
const nationals=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork')));
const ref138=nationals.items.find(i=>i.id==='nats-east-2026-cone-138'),ref139=nationals.items.find(i=>i.id==='nats-east-2026-cone-139');
assert.ok(Math.abs(Math.hypot(ref138.x-ref139.x,ref138.z-ref139.z)/.3048-75)<1e-8);
const ref102=nationals.items.find(i=>i.id==='nats-east-2026-cone-102');
assert.ok(Math.abs(ref102.x/7.62-Math.round(ref102.x/7.62))<1e-8);
assert.ok(Math.abs(ref102.z/7.62-Math.round(ref102.z/7.62))<1e-8);
assert.equal(nationals.viewAngle,0);
assert.equal(nationals.items.filter(i=>i.kind==='start').length,1);
assert.equal(nationals.items.filter(i=>i.kind==='stage').length,1);
assert.equal(nationals.items.filter(i=>i.kind==='finish').length,0);
// Hit-testing and dragging must follow the fitted PDF view.
const box=await page.locator('#map').boundingBox();
const angle=nationals.viewAngle*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle);
const corners=[[0,0],[nationals.columns*7.62,0],[0,nationals.rows*7.62],[nationals.columns*7.62,nationals.rows*7.62]].map(([x,y])=>[x*cos-y*sin,x*sin+y*cos]);
const minX=Math.min(...corners.map(p=>p[0])),maxX=Math.max(...corners.map(p=>p[0])),minY=Math.min(...corners.map(p=>p[1])),maxY=Math.max(...corners.map(p=>p[1]));
const sc=Math.min((box.width-100)/(maxX-minX),(box.height-100)/(maxY-minY));
const offsetX=(box.width-(maxX-minX)*sc)/2-minX*sc,offsetY=(box.height-(maxY-minY)*sc)/2-minY*sc;
const target=nationals.items.find(i=>i.id==='nats-east-2026-cone-130');
const sx=box.x+offsetX+(target.x*cos-target.z*sin)*sc,sy=box.y+offsetY+(target.x*sin+target.z*cos)*sc;
await page.mouse.move(sx,sy);await page.mouse.down();await page.mouse.move(sx+35,sy-25,{steps:5});await page.mouse.up();
const moved=JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))).items.find(i=>i.id===target.id);
assert.notEqual(moved.x,target.x);assert.notEqual(moved.z,target.z);
await page.locator('#undo').click();assert.deepEqual(JSON.parse(await page.evaluate(()=>localStorage.getItem('padwork'))),nationals);
await page.screenshot({path:'/tmp/padwork-demo.png'});
await page.locator('#preview').click();await page.locator('#three canvas').waitFor();await page.waitForTimeout(1000);await page.screenshot({path:'/tmp/padwork-3d.png'});await page.locator('#close-preview').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/padwork-mobile.png'});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.ok(await page.locator('[data-tool=pointer]').isVisible());
assert.deepEqual(errors,[]);
console.log('Browser checks passed: placement, history, gates, rotation, persistence, ZIP download, example, WebGL preview.');
await browser.close();
